package:
  name: "{{cookiecutter.project_slug}}"
  version: "{{cookiecutter.version}}"

source:
  # Relative path to the parent directory.
  path: ..

requirements:
  host:
    - python
    - setuptools
  build:
    {% raw -%}
    - python {{ python }}
    {%- endraw %}
  run:
    - python
    {# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build -#}
    {% raw -%}
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {%- endraw %}
    # - dependencyPackage1
    # - dependencyPackage2
    # ...

about:
  home: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
  license: {{ cookiecutter.open_source_license }}
  license_familY: {{ cookiecutter.open_source_license }}
  license_file: LICENSE
  summary: "{{ cookiecutter.project_short_description }}"

extra:
  recipe-maintainers:
    - {{ cookiecutter.github_username }}